Prep cloud.gcp_ops 1.0.0
redhat-cop/cloud.gcp_ops pull request #12
Opened 2024-01-31 16:55 UTC by alinabuzachis

2024-02-05 18:28 UTC, hakbailey requested changes
Don't we also need a CHANGELOG.rst? Other than that and updating the release date this looks good.

2024-02-06 09:55 UTC, alinabuzachis commented
> Don't we also need a CHANGELOG.rst? Other than that and updating the release date this looks good.

Done! Forgot to commit, thanks!

2024-02-06 14:58 UTC, hakbailey approved these changes
👍

2024-02-06 19:19 UTC, mandar242 approved these changes

2024-02-07 11:39 UTC, merged